name: CI

on:
  push:
    branches: ["main"]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .Net
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: dotnet build
        run: dotnet build ./src/Emergency.Responder/Emergency.Responder.sln --configuration Release

      - name: dotnet test
        run: dotnet test ./src/Emergency.Responder/Emergency.Responder.sln --configuration Release

      - name: dotnet publish
        run: dotnet publish ./src/Emergency.Responder/Emergency.Responder.Api/Emergency.Responder.Api.csproj --configuration Release -o artifacts

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: emergency-responder-app-artifact
          path: artifacts/

  deploy_dev:
    name: deploy dev
    needs: build
    uses: ./.github/workflows/step-deploy.yml
    with:
      env: dev
    secrets: inherit

  deploy_prod:
    name: deploy prod
    needs: deploy_dev
    uses: ./.github/workflows/step-deploy.yml
    with:
      env: prod
    secrets: inherit
