name: Publish

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  AZURE_WEB_APP_NAME: web-emergency-app
  AZURE_WEB_APP_PACKAGE_PATH: "./publish"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .Net
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x.x'

      - name: Restore
        run: dotnet restore ./src/Emergency.Responder/Emergency.Responder.sln

      - name: Build
        run: dotnet build ./src/Emergency.Responder/Emergency.Responder.sln --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./src/Emergency.Responder/Emergency.Responder.sln --configuration Release --no-build --output '${{env.AZURE_WEB_APP_PACKAGE_PATH}}' 

      - name: Deployment
        uses: actions/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEB_APP_NAME }}
          publish-profile: ${{secrets.AZURE_PUBLISH_PROFILE}}
          package: "${{ env.AZURE_WEB_APP_PACKAGE_PATH }}"
