name: Pull Request

on:
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: PR Verify
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .Net
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: dotnet build
        run: dotnet build ./src/Emergency.Responder/Emergency.Responder.sln --configuration Release

      - name: dotnet test
        run: dotnet test ./src/Emergency.Responder/Emergency.Responder.sln --configuration Release --no-build

      - name: dotnet format
        run: dotnet format -v detailed --verify-no-changes ./src/Emergency.Responder/Emergency.Responder.sln
